### ISSUE TITLE
Not Working Mods

### ISSUE THREAD

**Issue by hicefox** [illusivesoulworks/radiantgear#10]
The dynamic light feature while in a Curios slot doesn't work with the mods "Dynamic Lights" and "Magnesium/Rubidium Dynamic Lights"

**Comment by TheIllusiveC4** [comment]
You'll have to be a little bit more specific, because those mods should be working based on my testing.

Please list the version of Curios, Dynamic Lights or Magnesium/Rubidium Dynamic Lights, and Forge that you are running.

In addition, please tell me which light sources you have tried and if you have properly configured them in the dynamic lighting mod of your choice. A full list of reproduction steps would be even better.

**Comment by hicefox** [comment]
Minecraft 1.19.2
Forge v. 43.2.2
Curios v. 5.1.1.0
Magnesium/Rubidium Dynamic lights v. 1.4.0
Dynamic Lights v. 1.19.2.1 (I don't use this mod, I just tried it wen it didn't work with Magnesium and find out it did't work neither. With Lucent v. 1.4.1 works perfectly.)


I created a profile in CurseForge with the same forge version in order to see if it was just an incompatibility issue with another mod in wich I download the following mods:

Configured v. 2.0.1
Curios API v. 5.1.1.0
Curious Lanterns v. 1.2.1
Magnesium/Rubidium Dynamic Lights v. 1.4.0
Oculus v. 1.2.8a
Radiant Gear v. 2.0.0
Rubidium v. 0.6.2

It doesn't work either.

The light source I tried is the vanilla lantern. In both mods the Dynamic Light function works, the problen is that it doesn't when the lantern is in the Curio slot. But with Lucent it just works fine.

About the configuiration, I have not configured nothing. I tried using Configured to try and change sommething but it's impossible since neither Magnesium/Rubidium Dynamic Lights or Radiant Gear have a config menu and the only configurable part in Curious Lanters is an option called "Should Swing". Maybe it's a thing I need to config in the mod folder? I don't know.

**Comment by TheIllusiveC4** [comment]
> Dynamic Lights v. 1.19.2.1 (I don't use this mod, I just tried it wen it didn't work with Magnesium and find out it did't work neither.

When you tried Dynamic Lights, do the lanterns give off dynamic lighting when held normally? From what I can tell, they shouldn't unless you configured it, so that's not actually a Radiant Gear issue.

As for Magnesium/Rubidium Dynamic Lights, since you're on 1.19.2, this issue makes sense now since that integration hasn't been updated for 1.19.2. When Radiant Gear updated, that mod wasn't on 1.19.2 yet so the integration wasn't included from previous versions. I'll work on updating that now that I know it's been released.

**Comment by hicefox** [comment]
In the Dynamic Lights mod the lantern has to be added in the config in order to have dynamic lighting (but I dont know how to do it) so I guess that's the problem with Dynamic Lights.

As for Magnesium/Rubidium Dynamic Lights, I'll wait until it's updated.

Thanks you for your help.

Happy New Year and all that.
